version: '3.8'
services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongodb_data:
